language: perl

cache:
  directories:
    - perl_modules

before_install:
  - cpanm local::lib
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

perl:
  - '5.24'

install:
  - cpanm --quiet --installdeps --notest .

script:
  - PERL5LIB=$PWD/lib:$PERL5LIB prove -v t
