openapi: 3.0.0
info:
  description: System for retrieving sequence and metadata concerning a reference sequence object by hash
  title: GA4GH Reference Sequence Retrieval API
  version: '0.1'

servers:
  -
    url: "https://seqapi.herokuapp.com"
    description: "Reference test implementation (HTTPS)"

paths:
  /sequence/{id} :
    get:
      summary: Get a sequence from a hash
      description: Retrieve a reference sequence using a cryptographic hash function such as sha1
      parameters:
        - in: path
          name: id
          schema:
            type: string
          example: "c8e76de5f86131da26e8dd163658290d"
          required: true
          description: The identifier to use. Should be a checksum hash
        - in: query
          name: start
          schema:
            type : integer
            format: int32
            minimum: 0
          description: Request a subsequence of the data (0-based)
        - in: query
          name: end
          schema:
            type : integer
            format: int32
            minimum: 1
          description: Request a subsequence of the data by specifying the end
        - in: query
          name: format
          schema:
            type : string
            enum : [txt]
          description: Request the format of data. Only use this if you cannot use the Accept header
        - in: header
          name: Range
          schema:
            type: string
            format: range
          description: "Specify a substring as a range not using query parameters. Note start is in Ensembl-style start coordinates i.e. the first base of a sequence is 1 not 0 as in the start parameter. Example is 'bytes: 1-10'"


      responses:
        '200':
          description: Successful retrieval of sequence. Returned as a single string with no line breaks
          content:
            text/plain:
              schema:
                type: string
                example: MSSPTPPGGQRTLQKRKQGSSQKVAASAPKKNTNSNNSILKIYSDEATGLRVDPLVVLFLAVGFIFSVVALHVISKVAGKLF
        '400':
          description: Invalid input; normally due to range parameter usage
        '404':
          description: Sequence was not found
        '415':
          description: The requested sequence formatting is not supported by the server
        '416':
          description: Invalid range request specified

  /metadata/{id} :
    get:
      summary: Get reference metadta from a hash
      description: Retrieve a reference metadata information using a cryptographic hash function such as sha1
      parameters:
        - in: path
          name: id
          schema:
            type: string
          example: "c8e76de5f86131da26e8dd163658290d"
          required: true
          description: The identifier to use. Should be a checksum hash
        - in: query
          name: format
          schema:
            type : string
            enum : [json]
          description: Request the format of data. Only use this if you cannot use the Accept header

      responses:
        '200':
          description: Successful retrieval of sequence metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
        '404':
          description: Sequence hash was not found

components:
  schemas:
    Metadata:
      type: object
      properties:
        id:
          type: string
          description: Query identifier
        length:
          type: integer
          format: int64
          description: An decimal integer of the length of the reference sequence
        aliases:
          type: array
          items:
            type: object
            properties:
              alias:
                type: string
                description: A known alias for the query
